on:
  schedule:
    - cron: "0 9 * * 0-6"
  workflow_dispatch:
  push:
    branches: 
      - master

name: "Update library"

jobs:
  curl-books:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: curl books
        run: sh fetch.sh
